PILOT-1390
PilotDataPlatform/search pull request #25
Opened 2022-08-16 00:18 UTC by afmam

## Summary

- Added endpoint for querying item activity logs (only for project container_type).

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1390

## Type of Change

- [X] New feature (non-breaking change which adds functionality)

## Testing

Are there any new or updated tests to validate the changes?

- [X] Yes
- [ ] No

## Test Directions

- Project activity logs will be viewable in a projects canvas under "Recent File Stream"

2022-08-18 11:36 UTC, mloshakov requested changes
Looks good, but I have two suggestions to fix.

2022-08-18 11:36 UTC, mloshakov commented on search/components/item_activity/crud/crud.py
> +        document['_source']['index'] = self.index
You don't need `index` in the document, it is not used in `items-activity-logs` response schemas or in the logic.

You can remove `_parse_document` as a whole.

2022-08-18 11:36 UTC, mloshakov commented on search/components/item_activity/filtering.py
> +        search_query.match_term('container_type', 'project')
I understand that the intent was to only show documents with `container_type` = `project`, but it is not obvious here.  I think it would be better applied in custom CRUD `list` method.

2022-08-18 17:04 UTC, afmam commented on search/components/item_activity/crud/crud.py
> +        document['_source']['index'] = self.index
Fixed this

2022-08-18 17:04 UTC, afmam commented on search/components/item_activity/filtering.py
> +        search_query.match_term('container_type', 'project')
Fixed this by keeping filtering in ItemActivityProjectFiltering class and using `container_type: str = Field('project', const=True)`, as discussed.

2022-08-18 17:40 UTC, vmoshynskyi commented on search/components/item_activity/filtering.py
> +        search_query.match_term('container_type', 'project')
I would suggest to keep it as it was, but change it to Enum value.
```
search_query.match_term('container_type', ContainerType.PROJECT.value)
```
There is no need of having an extra if that will be always true as well as const field since we don't pass that value from query params.
With Enum it's easier to keep track where those keywords are used, instead of having a string value.

2022-08-18 19:06 UTC, afmam commented on search/components/item_activity/filtering.py
> +        search_query.match_term('container_type', 'project')
@vmoshynskyi Good point, I updated the code to use the Enum value. Because the `container_type` is not in the query params, the crud was also updated to ensure `filtering.apply(search_query)` is still executed: https://github.com/PilotDataPlatform/search/pull/25/commits/c63f2ee358e0d13046005765004aed2f99995bf7#diff-44ad60fe67557448257da73e88d75fb367e875005da72dbb551cac955651516bR131

2022-08-19 14:06 UTC, mloshakov approved these changes
LGTM now

2022-08-19 17:15 UTC, merged