PILOT-1533 Search items by attributes
PilotDataPlatform/search pull request #32
Opened 2022-08-24 13:37 UTC by erikdvlp

## Summary

- Allow searching ElasticSearch `metadata-items` by attribute values.

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1533

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Testing

Are there any new or updated tests to validate the changes?

- [x] Yes

## Test Directions

N/A

2022-08-26 09:01 UTC, mloshakov commented on search/components/metadata_item/parameters.py
> +            except Exception:
```suggestion
            except ValueError:
```

2022-08-26 09:04 UTC, mloshakov commented on search/components/metadata_item/parameters.py
> +                raise HTTPException(422, detail=param_validation_error('attributes', 'Must be valid JSON'))
Here you don't need to raise `HTTPException`, but `ValueError` with the custom message.

2022-08-26 09:06 UTC, mloshakov commented on search/components/metadata_item/filtering.py
> +    attributes: dict | None = None
```suggestion
    attributes: dict[str, Any] | None = None
```

2022-08-26 09:07 UTC, mloshakov commented on search/components/metadata_item/models.py
> +    attributes: dict | None
```suggestion
    attributes: dict[str, Any] | None
```

2022-08-26 09:08 UTC, mloshakov commented on search/components/metadata_item/schemas.py
> +    attributes: dict | None
```suggestion
    attributes: dict[str, Any] | None
```

2022-08-26 09:09 UTC, mloshakov commented on tests/fixtures/components/metadata_item.py
> +        attributes: dict | None = ...,
```suggestion
        attributes: dict[str, Any] | None = ...,
```

2022-08-26 09:11 UTC, mloshakov commented on tests/fixtures/components/metadata_item.py
> +        attributes: dict = ...,
```suggestion
        attributes: dict[str, Any] | None = ...,
```

2022-08-26 09:12 UTC, mloshakov commented on tests/fixtures/components/metadata_item.py
> +        attributes: dict = ...,
```suggestion
        attributes: dict[str, Any] | None = ...,
```

2022-08-26 13:07 UTC, erikdvlp commented on search/components/metadata_item/parameters.py
> +                raise HTTPException(422, detail=param_validation_error('attributes', 'Must be valid JSON'))
Usually yes, but Pydantic validators are meant to operate on the JSON body of a POST/PUT/PATCH/DELETE call, not the params of a GET call. If I throw a `ValueError` here, only a 500 with no description will be returned to the client. See [this discussion](https://github.com/tiangolo/fastapi/issues/318) for example.

As a way around it, I'm directing throwing an `HTTPException` so the client gets a 422 and a description.

2022-08-26 13:08 UTC, erikdvlp commented on search/components/metadata_item/parameters.py
> +            except Exception:
See `ValueError` thread below.

2022-08-29 08:18 UTC, mloshakov commented on search/components/metadata_item/parameters.py
> +                raise HTTPException(422, detail=param_validation_error('attributes', 'Must be valid JSON'))
Ah, okay. Still, there is a better way to do it.

See https://github.com/PilotDataPlatform/project/pull/19 by Hugo, specifically this part https://github.com/PilotDataPlatform/project/pull/19/files#diff-1384eb1db34f96576150f8e4e901eb262f08ae190f77fc4d9b3e3c616763ab4cR115

2022-08-29 08:19 UTC, mloshakov requested changes
See this comment https://github.com/PilotDataPlatform/search/pull/32#discussion_r957025000

2022-08-29 16:44 UTC, mloshakov approved these changes
👍

2022-08-29 16:44 UTC, merged